import useForm from './Main';
import * as CONSTANTS from './helpers/constants';

export default useForm;

export const FORM_CONSTANTS = {
  VIEW_MODE: CONSTANTS.VIEW_MODE,
  EDIT_MODE: CONSTANTS.EDIT_MODE,
  MESSAGE_TYPE: CONSTANTS.MESSAGE_TYPE,
  TEXT_TYPE: CONSTANTS.TEXT_TYPE,
  NUMBER_TYPE: CONSTANTS.NUMBER_TYPE,
  PASSWORD_TYPE: CONSTANTS.PASSWORD_TYPE,
  NOTE_TYPE: CONSTANTS.NOTE_TYPE,
  TOGGLE_TYPE: CONSTANTS.TOGGLE_TYPE,
  RADIO_TYPE: CONSTANTS.RADIO_TYPE,
  CHECKBOX_TYPE: CONSTANTS.CHECKBOX_TYPE,
  SINGLE_SELECT_TYPE: CONSTANTS.SINGLE_SELECT_TYPE,
  SEMANTIC_THEME: CONSTANTS.SEMANTIC_THEME,
};
