name: Publish
on: push
env:
  NODE_VERSION: '10.x'
jobs:
  publish-storybook:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
       run: npm install & npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs
